export const FETCH_IMTS = 'FETCH_IMTS'




export const FETCH_ORDERS = 'FETCH_ORDERS'
export const ADD_ORDER = 'ADD_ORDER'
export const UPDATE_ORDER = 'UPDATE_ORDER'
export const DELETE_ORDER = 'DELETE_ORDER'

export const FETCH_BREADCRUM = 'FETCH_BREADCRUM'
export const ADD_BREADCRUM = 'ADD_BREADCRUM'